### PR TITLE
Update lang.php

### PR DESCRIPTION
**Pull request by tachtler**
Hi, 

added the word "damit", because its sounds a little bit better in germen, and google.de use this wording too.

Klaus.

### CODE REVIEW

**Comment by Werkov** [comment]
Thanks, that's well beyond my knowledge of German language.

**Comment by tachtler** [comment]
Hi Michal,

thanks for the Plugin, my collegue and friend "Django-BofH", he made the good initial translation, send me the link to GitHub! (nice css too). 

But maybe, you can expand the a configuration section inside the DokuWiki Plugin Configuration, to override the text manually?

Klaus.

**Comment by Werkov** [comment]
Hello Klaus,
it's on my todolist (#2), however, it currently has superlow priority due to my other duties. So, any PRs are welcomed :-)

Michal

**Comment by tachtler** [comment]
Hallo Michal,

> Hello Klaus,
> it's on my todolist (#2), however, it currently has superlow  
> priority due to my other duties. So, any PRs are welcomed :-)

no Problem, this is NOT so important, but when you finde the time...  
it will be a great benefit.

> Michal
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/fykosak/dokuwiki-plugin-cookielaw/pull/8#issuecomment-142859075

Klaus.

## 

---

e-Mail  : klaus@tachtler.net
Homepage: http://www.tachtler.net

## DokuWiki: http://www.dokuwiki.tachtler.net

**Pull request merged**
